# 数据库参数
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/big_data_excel_local?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver

# 应用访问路径
server:
  port: 8082
  servlet:
    context-path: /big-data-excel

# 日志配置
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    jdbc.sqlonly: debug
    jdbc.resultsettable: debug
    org.hibernate.SQL: debug