debug: true

server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
    basedir: ./
    accesslog:
      enabled: true
      request-attributes-enabled: true
  compression:
    enabled: true
  servlet:
    context-path: /big-data-excel

spring:
  application:
    name: big-data-excel-server
  profiles:
    active: local
  jpa:
    properties:
      hibernate.enable_lazy_load_no_trans: true
  output:
    ansi:
      enabled: detect
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dbcp2:
      max-idle: 10
      max-total: 50
      max-wait-millis: 10000
      initial-size: 5
    hikari:
      read-only: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 60
      minimum-idle: 10

logging:
  level:
    com.landon: warn
    org.hibernate.SQL: error
    jdbc.sqlonly: error
    jdbc.resultsettable: error
    jdbc.audit: error
    jdbc.resultset: error
    jdbc.sqltiming: error
    jdbc.connection: error
    org.springframework.web.servlet: warn
    org.springframework.boot.actuate.endpoint.mvc: warn
    springfox.documentation: warn
    com.zaxxer.hikari.pool.HikariPool: warn
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: warn
    org.springframework.boot.actuate.endpoint.web.servlet.ControllerEndpointHandlerMapping: warn
    org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping: warn
    org.springframework.boot.web.servlet.filter.OrderedRequestContextFilter: warn
  file:
    name: ./logs/big-data-excel-server.log